name: Deploy Vue 3 App to GitHub Pages

on:
  push:
    branches:
      - main # Or your main branch name (e.g., master)

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build Vue 3 app
        run: npm run build

      - name: Prepare deploy folder
        run: |
          mv dist public_dist
          rm -rf * .[^.]*
          mv public_dist dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist